apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: backend-apis-team-settings
  namespace: backend-apis-team
spec:
  exportTo:
    - workspaces:
      - name: web-frontend-team
      resources:
        - kind: SERVICE
  options:
    eastWestGateways:
      - selector:
          labels:
            istio: eastwestgateway
    federation:
      enabled: false