apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: global-cert-issuer
  namespace: gloo-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    email: kasun.talwatta@solo.io
    privateKeySecretRef:
      name: global-cert-issuer
    solvers:
    - dns01:
        route53:
          region: $CLUSTER_REGION