apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: vs-postman-echo
  namespace: apps-configuration
spec:
  displayName: postman-echo
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
        - prefix: /
        routeAction:
          single:
            upstream:
              name: postman-echo-upstream
              namespace: apps-configuration
    options:
      stagedTransformations:
        early:
          requestTransforms:
            - matcher:
                prefix: '/'
              requestTransformation:
                transformationTemplate:
                  extractors:
                    ## Extractors for user-agent header
                    userAgentOSExtractor:
                      header: 'User-Agent'
                      regex: '.*?(iPad|iPhone|iphone|iPod).*?(OS |os |OS_).*?([[:digit:]]+((_|\.)[[:digit:]])?((_|\.)[[:digit:]])?).*?'
                      subgroup: 3
                  headers:
                    userAgentOS:
                      text: '{{ userAgentOSExtractor }}'
          responseTransforms:
            - responseTransformation:
                transformationTemplate:
                  headers:
                    x-solo-user-agent:
                      text: '{{ request_header("userAgentOS") }}'
                    ## If user-agent doesnt meet the version then reject request
                    ":status":
                      text: '{% if request_header("userAgentOS") != "10.1.2" %}400{% else %}{{ header(":status") }}{% endif %}'