apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: ext-auth-policy
  namespace: web-frontend-team
spec:
  applyToRoutes:
    - route:
        labels:
          enableExtAuth: "true"
  config:
    server:
      cluster: ${WEST_MESH_NAME}
      name: ext-auth-server
      namespace: ops-team
    glooAuth:
      configs:
        - oauth2:
            oidcAuthorizationCode:
              appUrl: https://apps.wooliesx.kasunt.fe.gl00.net
              callbackPath: /callback
              clientId: "${GOOGLE_OIDC_CLIENTID}"
              clientSecretRef:
                name: google-oidc
                namespace: web-frontend-team
              issuerUrl: https://accounts.google.com
              scopes:
                - email
              session:
                cookieOptions:
                  notSecure: true
              headers:
                idTokenHeader: jwt