apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: productpage-route-table
  namespace: web-frontend-team
  labels:
    # To auto export
    # workspace.solo.io/exported: "true"
    exposeResource: "true"
spec:
  hosts:
    - '*'
  virtualGateways:
    - name: north-south-gateway
      namespace: ops-team
      cluster: ${WEST_MESH_NAME}
  workloadSelectors: []
  http:
    - name: productpage
      labels:
        enableExtAuth: "true"
      matchers:
        - uri:
            exact: /productpage
        - uri:
            prefix: /static
        - uri:
            exact: /login
        - uri:
            exact: /logout
        - uri:
            prefix: /api/v1/products
        - uri:
            prefix: /callback
      forwardTo:
        destinations:
          - ref:
              name: productpage
              namespace: bookinfo-frontends
            port:
              number: 9080