glooEdge:
  enabled: true
licenseKey:
  secretRef:
    name: license
    namespace: gloo-system
    key: license-key
monetization:
  enabled: true
  configMapName: monetization-config
  secretName: monetization-secret