apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: reviews-route-rt
  namespace: backend-apis-team
spec:
  hosts:
    - 'reviews.bookinfo-backends.svc.cluster.local'
  workloadSelectors:
    - selector:
        labels:
          app: productpage
  http:
    - name: reviews
      matchers:
        - uri:
            prefix: /
      forwardTo:
        destinations:
          - ref:
              name: reviews-route-vd
            kind: VIRTUAL_DESTINATION
            port:
              number: 9080