apiVersion: resilience.policy.gloo.solo.io/v2
kind: OutlierDetectionPolicy
metadata:
  name: reviews-outlier-detection
  namespace: backend-apis-team
spec:
  applyToDestinations:
    - selector:
        name: reviews-route-vd
      kind: VIRTUAL_DESTINATION
      port:
        number: 9080
  config:
    consecutiveErrors: 2
    interval: 5s
    baseEjectionTime: 30s
    maxEjectionPercent: 100