apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  name: reviews-route-vd
  namespace: backend-apis-team
spec:
  hosts:
    - 'reviews-lb.bookinfo-backends.svc.cluster.local'
  ports:
    - number: 9080
      protocol: HTTP
      targetPort:
        number: 9080
  services:
    - labels:
        app: reviews
      namespace: bookinfo-backends